---
- name: install python
  hosts: all
  gather_facts: false
  tasks:
    - name: install python 2.x
      raw: test -e /usr/bin/python || (apt update && apt install -y python-simplejson)
      register: test
      changed_when: test.stdout

- name: install docker
  hosts: all
  tags:
    - docker
  roles:
    - docker

- name: setup backend
  hosts: backend
  tags:
    - api
  roles:
    - api

- name: setup frontend
  hosts: frontend
  tags:
    - ui
  roles:
    - ui

- name: setup sentry
  hosts: sentry
  tags:
    - sentry
  roles:
    - Stouts.sentry

- name: setup metrics
  hosts: metrics
  tags:
    - metrics
  roles:
    - prometheus
    - grafana

- name: setup balancer
  hosts: balancer
  tags:
    - balancer
  roles:
    - nginx
